### PR TITLE
support java11 sdk30 compile

### PR DESCRIPTION
**Pull request by tenwx**

### CODE REVIEW

**Comment by kasnder** [comment]
Thanks!

**Comment by SekiBetu** [comment]
can we have a release apk?

**Comment by kasnder** [comment]
> can we have a release apk?

Added this here now: https://github.com/kasnder/JustTrustMe/releases/tag/v.3

**Comment by SekiBetu** [comment]
> > can we have a release apk?
> 
> Added this here now: https://github.com/kasnder/JustTrustMe/releases/tag/v.3

thanks！

**Pull request merged**
